<?php
/**
 * Defines the default values for the "Typography" properties in desktop.
 *
 * @since 4.3.0
 * @package Hustle
 */

return array(
	'title_font_size_mobile'                               => '',
	'title_font_size_unit_mobile'                          => 'px',
	'title_font_weight_mobile'                             => 700,
	'title_alignment_mobile'                               => 'left',
	'title_line_height_mobile'                             => '',
	'title_line_height_unit_mobile'                        => 'px',
	'title_letter_spacing_mobile'                          => '',
	'title_letter_spacing_unit_mobile'                     => 'px',
	'title_text_transform_mobile'                          => 'none',
	'title_text_decoration_mobile'                         => 'none',

	'subtitle_font_size_mobile'                            => '',
	'subtitle_font_size_unit_mobile'                       => 'px',
	'subtitle_font_weight_mobile'                          => 700,
	'subtitle_alignment_mobile'                            => 'left',
	'subtitle_line_height_mobile'                          => '',
	'subtitle_line_height_unit_mobile'                     => 'px',
	'subtitle_letter_spacing_mobile'                       => '',
	'subtitle_letter_spacing_unit_mobile'                  => 'px',
	'subtitle_text_transform_mobile'                       => 'none',
	'subtitle_text_decoration_mobile'                      => 'none',

	'main_content_paragraph_font_size_mobile'              => '',
	'main_content_paragraph_font_size_unit_mobile'         => 'px',
	'main_content_paragraph_font_weight_mobile'            => 'regular',
	'main_content_paragraph_alignment_mobile'              => 'left',
	'main_content_paragraph_line_height_mobile'            => '',
	'main_content_paragraph_line_height_unit_mobile'       => 'em',
	'main_content_paragraph_letter_spacing_mobile'         => '',
	'main_content_paragraph_letter_spacing_unit_mobile'    => 'px',
	'main_content_paragraph_text_transform_mobile'         => 'none',
	'main_content_paragraph_text_decoration_mobile'        => 'none',

	'main_content_heading_one_font_size_mobile'            => '',
	'main_content_heading_one_font_size_unit_mobile'       => 'px',
	'main_content_heading_one_font_weight_mobile'          => 700,
	'main_content_heading_one_alignment_mobile'            => 'left',
	'main_content_heading_one_line_height_mobile'          => '',
	'main_content_heading_one_line_height_unit_mobile'     => 'em',
	'main_content_heading_one_letter_spacing_mobile'       => '',
	'main_content_heading_one_letter_spacing_unit_mobile'  => 'px',
	'main_content_heading_one_text_transform_mobile'       => 'none',
	'main_content_heading_one_text_decoration_mobile'      => 'none',

	'main_content_heading_two_font_size_mobile'            => '',
	'main_content_heading_two_font_size_unit_mobile'       => 'px',
	'main_content_heading_two_font_weight_mobile'          => 700,
	'main_content_heading_two_alignment_mobile'            => 'left',
	'main_content_heading_two_line_height_mobile'          => '',
	'main_content_heading_two_line_height_unit_mobile'     => 'em',
	'main_content_heading_two_letter_spacing_mobile'       => '',
	'main_content_heading_two_letter_spacing_unit_mobile'  => 'px',
	'main_content_heading_two_text_transform_mobile'       => 'none',
	'main_content_heading_two_text_decoration_mobile'      => 'none',

	'main_content_heading_three_font_size_mobile'          => '',
	'main_content_heading_three_font_size_unit_mobile'     => 'px',
	'main_content_heading_three_font_weight_mobile'        => 700,
	'main_content_heading_three_alignment_mobile'          => 'left',
	'main_content_heading_three_line_height_mobile'        => '',
	'main_content_heading_three_line_height_unit_mobile'   => 'em',
	'main_content_heading_three_letter_spacing_mobile'     => '',
	'main_content_heading_three_letter_spacing_unit_mobile' => 'px',
	'main_content_heading_three_text_transform_mobile'     => 'none',
	'main_content_heading_three_text_decoration_mobile'    => 'none',

	'main_content_heading_four_font_size_mobile'           => '',
	'main_content_heading_four_font_size_unit_mobile'      => 'px',
	'main_content_heading_four_font_weight_mobile'         => 700,
	'main_content_heading_four_alignment_mobile'           => 'left',
	'main_content_heading_four_line_height_mobile'         => '',
	'main_content_heading_four_line_height_unit_mobile'    => 'em',
	'main_content_heading_four_letter_spacing_mobile'      => '',
	'main_content_heading_four_letter_spacing_unit_mobile' => 'px',
	'main_content_heading_four_text_transform_mobile'      => 'none',
	'main_content_heading_four_text_decoration_mobile'     => 'none',

	'main_content_heading_five_font_size_mobile'           => '',
	'main_content_heading_five_font_size_unit_mobile'      => 'px',
	'main_content_heading_five_font_weight_mobile'         => 700,
	'main_content_heading_five_alignment_mobile'           => 'left',
	'main_content_heading_five_line_height_mobile'         => '',
	'main_content_heading_five_line_height_unit_mobile'    => 'em',
	'main_content_heading_five_letter_spacing_mobile'      => '',
	'main_content_heading_five_letter_spacing_unit_mobile' => 'px',
	'main_content_heading_five_text_transform_mobile'      => 'none',
	'main_content_heading_five_text_decoration_mobile'     => 'none',

	'main_content_heading_six_font_size_mobile'            => '',
	'main_content_heading_six_font_size_unit_mobile'       => 'px',
	'main_content_heading_six_font_weight_mobile'          => 700,
	'main_content_heading_six_alignment_mobile'            => 'left',
	'main_content_heading_six_line_height_mobile'          => '',
	'main_content_heading_six_line_height_unit_mobile'     => 'em',
	'main_content_heading_six_letter_spacing_mobile'       => '',
	'main_content_heading_six_letter_spacing_unit_mobile'  => 'px',
	'main_content_heading_six_text_transform_mobile'       => 'uppercase',
	'main_content_heading_six_text_decoration_mobile'      => 'none',

	'main_content_lists_font_size_mobile'                  => '',
	'main_content_lists_font_size_unit_mobile'             => 'px',
	'main_content_lists_font_weight_mobile'                => 'regular',
	'main_content_lists_alignment_mobile'                  => 'left',
	'main_content_lists_line_height_mobile'                => '',
	'main_content_lists_line_height_unit_mobile'           => 'em',
	'main_content_lists_letter_spacing_mobile'             => '',
	'main_content_lists_letter_spacing_unit_mobile'        => 'px',
	'main_content_lists_text_transform_mobile'             => 'none',
	'main_content_lists_text_decoration_mobile'            => 'none',

	'cta_font_size_mobile'                                 => '',
	'cta_font_size_unit_mobile'                            => 'px',
	'cta_font_weight_mobile'                               => 'bold',
	'cta_alignment_mobile'                                 => 'center',
	'cta_line_height_mobile'                               => '',
	'cta_line_height_unit_mobile'                          => 'px',
	'cta_letter_spacing_mobile'                            => '',
	'cta_letter_spacing_unit_mobile'                       => 'px',
	'cta_text_transform_mobile'                            => 'none',
	'cta_text_decoration_mobile'                           => 'none',
	'cta_font_size_mobile'                                 => '',

	'cta_help_font_size_mobile'                            => '',
	'cta_help_font_size_unit_mobile'                       => 'px',
	'cta_help_font_weight_mobile'                          => 'regular',
	'cta_help_alignment_mobile'                            => 'left',
	'cta_help_line_height_mobile'                          => '',
	'cta_help_line_height_unit_mobile'                     => 'em',
	'cta_help_letter_spacing_mobile'                       => '',
	'cta_help_letter_spacing_unit_mobile'                  => 'px',
	'cta_help_text_transform_mobile'                       => 'none',
	'cta_help_text_decoration_mobile'                      => 'none',

	'never_see_link_font_size_mobile'                      => '',
	'never_see_link_font_size_unit_mobile'                 => 'px',
	'never_see_link_font_weight_mobile'                    => 'regular',
	'never_see_link_alignment_mobile'                      => 'center',
	'never_see_link_line_height_mobile'                    => '',
	'never_see_link_line_height_unit_mobile'               => 'px',
	'never_see_link_letter_spacing_mobile'                 => '',
	'never_see_link_letter_spacing_unit_mobile'            => 'px',
	'never_see_link_text_transform_mobile'                 => 'none',
	'never_see_link_text_decoration_mobile'                => 'none',

	'form_extras_font_size_mobile'                         => '',
	'form_extras_font_size_unit_mobile'                    => 'px',
	'form_extras_font_weight_mobile'                       => 'bold',
	'form_extras_alignment_mobile'                         => 'left',
	'form_extras_line_height_mobile'                       => '',
	'form_extras_line_height_unit_mobile'                  => 'px',
	'form_extras_letter_spacing_mobile'                    => '',
	'form_extras_letter_spacing_unit_mobile'               => 'px',
	'form_extras_text_transform_mobile'                    => 'none',
	'form_extras_text_decoration_mobile'                   => 'none',

	'input_font_size_mobile'                               => '',
	'input_font_size_unit_mobile'                          => 'px',
	'input_font_weight_mobile'                             => 'regular',
	'input_alignment_mobile'                               => 'left',
	'input_line_height_mobile'                             => '',
	'input_line_height_unit_mobile'                        => 'px',
	'input_letter_spacing_mobile'                          => '',
	'input_letter_spacing_unit_mobile'                     => 'px',
	'input_text_transform_mobile'                          => 'none',
	'input_text_decoration_mobile'                         => 'none',

	'select_font_size_mobile'                              => '',
	'select_font_size_unit_mobile'                         => 'px',
	'select_font_weight_mobile'                            => 'regular',
	'select_alignment_mobile'                              => 'left',
	'select_line_height_mobile'                            => '',
	'select_line_height_unit_mobile'                       => 'px',
	'select_letter_spacing_mobile'                         => '',
	'select_letter_spacing_unit_mobile'                    => 'px',
	'select_text_transform_mobile'                         => 'none',
	'select_text_decoration_mobile'                        => '',

	'checkbox_font_size_mobile'                            => '',
	'checkbox_font_size_unit_mobile'                       => 'px',
	'checkbox_font_weight_mobile'                          => 'regular',
	'checkbox_alignment_mobile'                            => 'left',
	'checkbox_line_height_mobile'                          => '',
	'checkbox_line_height_unit_mobile'                     => 'px',
	'checkbox_letter_spacing_mobile'                       => '',
	'checkbox_letter_spacing_unit_mobile'                  => 'px',
	'checkbox_text_transform_mobile'                       => 'none',
	'checkbox_text_decoration_mobile'                      => 'none',

	'dropdown_font_size_mobile'                            => '',
	'dropdown_font_size_unit_mobile'                       => 'px',
	'dropdown_font_weight_mobile'                          => 'regular',
	'dropdown_alignment_mobile'                            => 'left',
	'dropdown_line_height_mobile'                          => '',
	'dropdown_line_height_unit_mobile'                     => 'px',
	'dropdown_letter_spacing_mobile'                       => '',
	'dropdown_letter_spacing_unit_mobile'                  => 'px',
	'dropdown_text_transform_mobile'                       => 'none',
	'dropdown_text_decoration_mobile'                      => 'none',

	'gdpr_font_size_mobile'                                => '',
	'gdpr_font_size_unit_mobile'                           => 'px',
	'gdpr_font_weight_mobile'                              => 'regular',
	'gdpr_alignment_mobile'                                => 'left',
	'gdpr_line_height_mobile'                              => '',
	'gdpr_line_height_unit_mobile'                         => 'em',
	'gdpr_letter_spacing_mobile'                           => '',
	'gdpr_letter_spacing_unit_mobile'                      => 'px',
	'gdpr_text_transform_mobile'                           => 'none',
	'gdpr_text_decoration_mobile'                          => 'none',

	'recaptcha_font_size_mobile'                           => '',
	'recaptcha_font_size_unit_mobile'                      => 'px',
	'recaptcha_font_weight_mobile'                         => 'regular',
	'recaptcha_alignment_mobile'                           => 'left',
	'recaptcha_line_height_mobile'                         => '',
	'recaptcha_line_height_unit_mobile'                    => 'em',
	'recaptcha_letter_spacing_mobile'                      => '',
	'recaptcha_letter_spacing_unit_mobile'                 => 'px',
	'recaptcha_text_transform_mobile'                      => 'none',
	'recaptcha_text_decoration_mobile'                     => 'none',

	'submit_button_font_size_mobile'                       => '',
	'submit_button_font_size_unit_mobile'                  => 'px',
	'submit_button_font_weight_mobile'                     => 'bold',
	'submit_button_line_height_mobile'                     => '',
	'submit_button_line_height_unit_mobile'                => 'px',
	'submit_button_letter_spacing_mobile'                  => '',
	'submit_button_letter_spacing_unit_mobile'             => 'px',
	'submit_button_text_transform_mobile'                  => 'none',
	'submit_button_text_decoration_mobile'                 => 'none',

	'success_message_paragraph_font_size_mobile'           => '',
	'success_message_paragraph_font_size_unit_mobile'      => 'px',
	'success_message_paragraph_font_weight_mobile'         => 'regular',
	'success_message_paragraph_alignment_mobile'           => 'left',
	'success_message_paragraph_line_height_mobile'         => '',
	'success_message_paragraph_line_height_unit_mobile'    => 'em',
	'success_message_paragraph_letter_spacing_mobile'      => '',
	'success_message_paragraph_letter_spacing_unit_mobile' => 'px',
	'success_message_paragraph_text_transform_mobile'      => 'none',
	'success_message_paragraph_text_decoration_mobile'     => 'none',

	'success_message_heading_one_font_size_mobile'         => '',
	'success_message_heading_one_font_size_unit_mobile'    => 'px',
	'success_message_heading_one_font_weight_mobile'       => 700,
	'success_message_heading_one_alignment_mobile'         => 'left',
	'success_message_heading_one_line_height_mobile'       => '',
	'success_message_heading_one_line_height_unit_mobile'  => 'em',
	'success_message_heading_one_letter_spacing_mobile'    => '',
	'success_message_heading_one_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_one_text_transform_mobile'    => 'none',
	'success_message_heading_one_text_decoration_mobile'   => 'none',

	'success_message_heading_two_font_size_mobile'         => '',
	'success_message_heading_two_font_size_unit_mobile'    => 'px',
	'success_message_heading_two_font_weight_mobile'       => 700,
	'success_message_heading_two_alignment_mobile'         => 'left',
	'success_message_heading_two_line_height_mobile'       => '',
	'success_message_heading_two_line_height_unit_mobile'  => 'em',
	'success_message_heading_two_letter_spacing_mobile'    => '',
	'success_message_heading_two_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_two_text_transform_mobile'    => 'none',
	'success_message_heading_two_text_decoration_mobile'   => 'none',

	'success_message_heading_three_font_size_mobile'       => '',
	'success_message_heading_three_font_size_unit_mobile'  => 'px',
	'success_message_heading_three_font_weight_mobile'     => 700,
	'success_message_heading_three_alignment_mobile'       => 'left',
	'success_message_heading_three_line_height_mobile'     => '',
	'success_message_heading_three_line_height_unit_mobile' => 'em',
	'success_message_heading_three_letter_spacing_mobile'  => '',
	'success_message_heading_three_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_three_text_transform_mobile'  => 'none',
	'success_message_heading_three_text_decoration_mobile' => 'none',

	'success_message_heading_four_font_size_mobile'        => '',
	'success_message_heading_four_font_size_unit_mobile'   => 'px',
	'success_message_heading_four_font_weight_mobile'      => 700,
	'success_message_heading_four_alignment_mobile'        => 'left',
	'success_message_heading_four_line_height_mobile'      => '',
	'success_message_heading_four_line_height_unit_mobile' => 'em',
	'success_message_heading_four_letter_spacing_mobile'   => '',
	'success_message_heading_four_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_four_text_transform_mobile'   => 'none',
	'success_message_heading_four_text_decoration_mobile'  => 'none',

	'success_message_heading_five_font_size_mobile'        => '',
	'success_message_heading_five_font_size_unit_mobile'   => 'px',
	'success_message_heading_five_font_weight_mobile'      => 700,
	'success_message_heading_five_alignment_mobile'        => 'left',
	'success_message_heading_five_line_height_mobile'      => '',
	'success_message_heading_five_line_height_unit_mobile' => 'em',
	'success_message_heading_five_letter_spacing_mobile'   => '',
	'success_message_heading_five_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_five_text_transform_mobile'   => 'none',
	'success_message_heading_five_text_decoration_mobile'  => 'none',

	'success_message_heading_six_font_size_mobile'         => '',
	'success_message_heading_six_font_size_unit_mobile'    => 'px',
	'success_message_heading_six_font_weight_mobile'       => 700,
	'success_message_heading_six_alignment_mobile'         => 'left',
	'success_message_heading_six_line_height_mobile'       => '',
	'success_message_heading_six_line_height_unit_mobile'  => 'em',
	'success_message_heading_six_letter_spacing_mobile'    => '',
	'success_message_heading_six_letter_spacing_unit_mobile' => 'px',
	'success_message_heading_six_text_transform_mobile'    => 'uppercase',
	'success_message_heading_six_text_decoration_mobile'   => 'none',

	'success_message_lists_font_size_mobile'               => '',
	'success_message_lists_font_size_unit_mobile'          => 'px',
	'success_message_lists_font_weight_mobile'             => 'regular',
	'success_message_lists_alignment_mobile'               => 'left',
	'success_message_lists_line_height_mobile'             => '',
	'success_message_lists_line_height_unit_mobile'        => 'em',
	'success_message_lists_letter_spacing_mobile'          => '',
	'success_message_lists_letter_spacing_unit_mobile'     => 'px',
	'success_message_lists_text_transform_mobile'          => 'none',
	'success_message_lists_text_decoration_mobile'         => 'none',

	'error_message_font_size_mobile'                       => '',
	'error_message_font_size_unit_mobile'                  => 'px',
	'error_message_font_weight_mobile'                     => 'regular',
	'error_message_alignment_mobile'                       => 'left',
	'error_message_line_height_mobile'                     => '',
	'error_message_line_height_unit_mobile'                => 'px',
	'error_message_letter_spacing_mobile'                  => '',
	'error_message_letter_spacing_unit_mobile'             => 'px',
	'error_message_text_transform_mobile'                  => 'none',
	'error_message_text_decoration_mobile'                 => 'none',
);
